# Define images and workspaces
node8: &node8
  working_directory: &workdir_node8 ~/node8
  docker:
    - image: circleci/node:8

# Branch and tag filters
tags_and_branches: &tags_and_branches
  filters:
    tags:
      only: /^v.*/

only_tags: &only_tags
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

# Items to persist from workspace
whitelist: &whitelist
  paths:
    - node_modules/*
    - bin/*
    - src/*
    - test/*
    - public/*
    - package.json
    - .eslintrc.js
    - webpack.config.js
    - .babelrc

version: 2
jobs:
  install:
    <<: *node8
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          - dependencies-{{ .Branch }}
          - dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: *workdir_node8
          <<: *whitelist
  build:
    <<: *node8
    steps:
      - attach_workspace:
          at: *workdir_node8
      - run: npm run build
  deploy:
    <<: *node8
    steps:
      - attach_workspace:
          at: *workdir_node8
      - restore_cache:
          keys:
          - repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo $DEPLOY_FILE | base64 --decode > ecosystem.deploy.json
      - run: sudo npm install -g pm2
      - run: pm2 deploy ecosystem.deploy.json production ref $CIRCLE_TAG
workflows:
  version: 2
  build_deploy:
    jobs:
      - install:
          <<: *tags_and_branches
      - build:
          <<: *tags_and_branches
          requires:
            - install
      - confirm_deploy:
          <<: *only_tags
          type: approval
          requires:
           - build
      - deploy:
          <<: *only_tags
          requires:
            - confirm_deploy
