# Define images and workspaces
node10: &node10
  working_directory: &workdir_node10 ~/node10
  docker:
    - image: circleci/node:10.14

# Branch and tag filters
tags_and_branches: &tags_and_branches
  filters:
    tags:
      only: /^v.*/

only_tags: &only_tags
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

# Items to persist from workspace
whitelist: &whitelist
  paths:
    - .git/*
    - node_modules/*
    - bin/*
    - src/*
    - test/*
    - public/*
    - package.json
    - package-lock.json
    - tslint.json
    - webpack.config.ts
    - tsconfig.json
    - jest.config.js

version: 2
jobs:
  install:
    <<: *node10
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-node_10.14-{{ .Branch }}-{{ checksum "package.json" }}
          - dependencies-node_10.14-{{ .Branch }}
          - dependencies-node_10.14
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-node_10.14-{{ .Branch }}-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: *workdir_node10
          <<: *whitelist
  test:
    <<: *node10
    steps:
      - attach_workspace:
          at: *workdir_node10
      - run: npm test
  build:
    <<: *node10
    steps:
      - attach_workspace:
          at: *workdir_node10
      - run: npm run build
  deploy:
    <<: *node10
    steps:
      - attach_workspace:
          at: *workdir_node10
      - run: echo $DEPLOY_FILE | base64 --decode > ecosystem.deploy.json
      - run: sudo npm install -g pm2
      - run: pm2 deploy ecosystem.deploy.json production ref origin/$CIRCLE_TAG --force
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install:
          <<: *tags_and_branches
      - test:
          <<: *tags_and_branches
          requires:
            - install
      - build:
          <<: *tags_and_branches
          requires:
            - install
      - confirm_deploy:
          <<: *only_tags
          type: approval
          requires:
           - build
      - deploy:
          <<: *only_tags
          requires:
            - confirm_deploy
